apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
        - name: "{{ .Name }}"
          image: { { .Image } }
          env:
            - name: TESTCONTAINERS_HOST_OVERRIDE
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
